### ISSUE TITLE
Tags/branches to track changes

### ISSUE THREAD

**Issue by ghost** [baikalelectronics/Linux-kernel.4.4.xx#1]
Hello!

I'm interested in Baikal-T1 support in other kernels (not only Linux) and I want to track changes in the kernel so it'll be possible to port it to BSDs, for example. Are there any branches or tags in the repository to filter the changes or all the development process is done in the `master` branch?

**Comment by baikalelectronics** [comment]
Hello!
The development is in a separate repository. We publish changes from the released SDK in the master branch only.
